<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

 /** @var $block \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files */

$_width  = $block->getImagesWidth();
$_height = $block->getImagesHeight();


?>
<?php if ($block->getFilesCount() > 0): ?>
    <?php foreach ($block->getFiles() as $file): ?>
    <?php $path_info = pathinfo($block->getFileName($file)); ?>
    <div data-row="file" class="filecnt" id="<?= $block->escapeHtmlAttr($block->getFileId($file)) ?>">
        <p class="nm" style="height:<?= $block->escapeHtmlAttr($_height) ?>px;width:<?= $block->escapeHtmlAttr($_width) ?>px;">
        <?php if ($block->getFileThumbUrl($file)):?>
            <?php if($path_info['extension'] == 'pdf'): ?>
                <img height="83px" src="https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/svgs/fi-page-pdf.svg"/>
            <?php else: ?>
            <img src="<?= $block->escapeHtmlAttr($block->getFileThumbUrl($file)) ?>" alt="<?= $block->escapeHtmlAttr($block->getFileName($file)) ?>"/>
            <?php endif; ?>
        <?php endif; ?>
        </p>
        <?php if ($block->getFileWidth($file)): ?>
            <small><?= $block->escapeHtml($block->getFileWidth($file)) ?>x<?= $block->escapeHtml($block->getFileHeight($file)) ?> <?= $block->escapeHtml(__('px.')) ?></small><br/>
        <?php endif; ?>
        <small><?= $block->escapeHtml($block->getFileShortName($file)) ?></small>
    </div>
    <?php endforeach; ?>
<?php else: ?>
    <div class="empty"><?= $block->escapeHtml(__('No files found')) ?></div>
<?php endif; ?>
